name: Proxy Checker

on:
  schedule:
    - cron: "0 0 * * 0"  # Jalankan setiap minggu (Minggu, 00:00 UTC)
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Proxy Checker
        run: python proxy_checker.py

      - name: Generate GitHub App Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Commit and Push if changed
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          set -e  # Hentikan script jika terjadi error
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Periksa apakah file proxy_list_active.txt ada
          if [[ ! -f proxy_list_active.txt ]]; then
            echo "File proxy_list_active.txt tidak ditemukan. Keluar."
            exit 1
          fi

          # Cek apakah ada perubahan sebelum commit
          if [[ `git status --porcelain proxy_list_active.txt` ]]; then
            echo "Ada perubahan pada proxy_list_active.txt. Melakukan commit dan push..."
            git add proxy_list_active.txt
            git commit -m "Update active proxy list"

            # Pastikan branch up-to-date sebelum push
            git fetch origin main
            git pull --rebase origin main || git reset --hard origin/main

            # Push perubahan
            git push origin main
          else
            echo "Tidak ada perubahan pada proxy_list_active.txt, tidak perlu commit."
          fi
